classDiagram

people <|-- doctor
people <|-- patient

class people {
  + id: id
  + name: String
  + phoneNumber: String
  + birthDate: Date
  + createdAt: DateTime
  + updatedAt: DateTime
  + gender: String
  + docNumber: String
  + fiscalNumber: int
  + socialSecurityNumber: int
}

class doctor {
}

class patient {
  + insuranceNumber: String
}


class appointment {
  + id: id
  + startDate: DateTime
  + endDate: DateTime
  + createdAt: DateTime
  + updatedAt: DateTime 
  + type: String
}

class specialty {
  + id: id
  + name: String
  + description: String
  + createdAt: DateTime
  + updatedAt: DateTime
}

 class idtype {
    <<enumeration>>         
    Passport         
    Citizen ID            
  }


doctor "*" -- "*" specialty 
appointment "*" -- "1" specialty


appointment "*" -- "1" doctor
appointment "*" -- "1" patient

people --> idtype