classDiagram

people <|-- doctor
people <|-- patient

class people {
  + id: id
  + name: String
  + phoneNumber: String
  + birthDate: Date
  + createdAt: Date
  + updatedAt: Date
  + gender: String
  + identification: identification
}

class doctor {
}

class patient {
  + insuranceNumber: String
}


class appointment {
  + id: id
  + date: Date
  + time: Time
  + createdAt: Date
  + updatedAt: Date
  + type: String
}

class specialty {
  + id: id
  + name: String
  + description: String
  + createdAt: Date
  + updatedAt: Date
}

 class idtype {
    <<enumeration>>         
    Passport         
    Citizen ID            
  }

class identification {
  + id: id
  + type: idtype
  + number: String
  + createdAt: Date
  + updatedAt: Date
}

doctor "*" -- "*" specialty 
appointment "*" -- "1" specialty


appointment "*" -- "1" doctor
appointment "*" -- "1" patient

people "1" -- "1" identification
identification --> idtype